### ISSUE TITLE
Network Meter: Bytes/sec display option

### ISSUE THREAD

**Issue by aniforprez** [iamanai/ModernGadgets#15]
Currently, the speed is indicated in bits per second but we should be able to select if we want to see it in bits or bytes.

Todo:
- [x] Implement toggle in settings
- [x] Add to import and defaults functions

**Comment by iamanai** [comment]
That is something that was planned, but I forgot to implement a setting for it! It'll come in v1.1.

**Comment by iamanai** [comment]
Todo:
- [ ] Implement toggle in settings
- [ ] Add to import and defaults functions

**Comment by iamanai** [comment]
Finally done. Sorry it took so long!

**Comment by aniforprez** [comment]
Yo awesome. Thanks!

**Comment by iamanai** [comment]
This feature has been released in v1.2.0-beta.2.
