### ISSUE TITLE
Script: UpdateChecker.lua:188 Could not extract version number from ""

### ISSUE THREAD

**Issue by aniforprez** [iamanai/ModernGadgets#32]
I'm getting this error when loading up Rainmeter on boot and Rainmeter refuses to load any skins when this happens. I need to end the Rainmeter process and start it up again when this happens.

**Comment by iamanai** [comment]
What the devil? This error is thrown when the comparison script is given something that's not a string. Does it happen every single time you boot the computer?

**Comment by aniforprez** [comment]
Ok it's not happening when I boot anymore but now it's happening occasionally when I turn my internet off and on. I'll add your code and see what happens next time it crashes

**Comment by aniforprez** [comment]
Ok I started Rainmeter when the system was offline and it managed to load all the skins but still threw the same error. I've also added the line you suggested. Here's the log from the logfiles

NOTE (09:54:52.522) ModernGadgets\Config\Setup\Config.ini: Refreshing skin
ERRO (09:54:52.540) ModernGadgets\Config\Setup\Config.ini - [MeasureUpdateWebParser]: (Fetch error) The server name or address could not be resolved  (ErrorCode=12007)
ERRO (09:54:52.546) ModernGadgets\Config\Setup\Config.ini: Could not connect to update server
ERRO (09:54:53.581) ModernGadgets\Config\Setup\Config.ini: 1.2.0 
ERRO (09:54:53.585) : Script: UpdateChecker.lua:189: Could not extract version number(s) from ""

**Comment by iamanai** [comment]
That's odd. The script should never be able to activate unless there are actual string values for both version numbers. I can't reproduce this, but I can see how it happens.

I'll look into it.

**Comment by iamanai** [comment]
If it's still happening, I would suggest turning off "check for updates" in the global settings skin, and just manually checking for updates on deviantart or the Rainmeter forums from time to time. I have only managed to reproduce this bug once, and I can't get it to do it again. Sorry.

**Comment by aniforprez** [comment]
Yeah it's not been a problem for a long time now. I think one of the updates fixed it. Sorry for not updating you

**Comment by iamanai** [comment]
Ah, that's good to know! No worries.
