### ISSUE TITLE
Network Meter Bytes/Sec setting does nothing other than change the units

### ISSUE THREAD

**Issue by aniforprez** [iamanai/ModernGadgets#36]
Turning Bytes/Sec on or off doesn't change the value of the current internet speed, only the value. It still shows the value in bits/sec instead of Bytes when turned on

With it on
https://gyazo.com/7165811f683d94adeb65459d7b6c4f8d

With it off
https://gyazo.com/14ba2068aff2998a240c5c3bbe941475

Note that only the peak values within the graph have changed to reflect the setting

**Comment by iamanai** [comment]
Welp... Turns out you're partially right. I forgot to make the script toggle the download rate's actual measures. I am facepalming so hard right now.

**Comment by iamanai** [comment]
Fixed in 1.2.1

**Comment by aniforprez** [comment]
Nice
