### ISSUE TITLE
Deluge-Rainmeter-Skin gadget

### ISSUE THREAD

**Issue by maxdd** [iamanai/ModernGadgets#40]
Great work so far,
as an added feature would it be possibile to add this gadget?

https://github.com/Tain101/Deluge-Rainmeter-Skin

It needs some aesthetic and yours seems really good

**Comment by iamanai** [comment]
I am not planning to add anything like that to ModernGadgets. However, Rainmeter is fairly simple to learn, so with some time I'm sure you could figure it out (or just use the existing one and modify the visuals). Cheers!
