### ISSUE TITLE
Disks meter always showing 100% usage

### ISSUE THREAD

**Issue by binary-idiot** [iamanai/ModernGadgets#41]
When I first started using this skin it worked fine, however now the disks meter will always show 100% usage, I've tried updating the skin, HWINFO, even rain meter, but nothing has fixed it. 
Also note, i don't think it would have caused it but between the time it stopped working and now, I've had an external HDD fail that i have since moved to internal

![modern gadgets](https://user-images.githubusercontent.com/13305186/28084749-a56530a6-6647-11e7-9b88-8a844beb4481.PNG)

**Comment by iamanai** [comment]
Hmm... it appears that the PerfMon database has become corrupted. Open cmd.exe as administrator and type in the following, in order:
```
cd c:\windows\system32
lodctr /R
cd c:\windows\sysWOW64
lodctr /R
```
You should then see the following:
`Info: Successfully rebuilt performance counter setting from system backup store`
After you do this, refresh Disks Meter and see if it fixed the problem.

On unrelated notes, it appears that you set the temperatures to Fahrenheit, but didn't actually go into HWiNFO to change it as well. Thus, your temperatures are still Celsius, but say they're Fahrenheit. Right-click on HWiNFO's tray icon, click 'Sensors', click the gear icon in the bottom right corner, and change the temperature option to Fahrenheit. Then it'll report the temperatures correctly.

Also your GPU fan speed should not be 0RPM. You should check to be sure HWiNFO is set up correctly.

**Comment by iamanai** [comment]
Did it work? I want to close the issue if it did.

**Comment by iamanai** [comment]
Closing the issue

**Comment by binary-idiot** [comment]
Thanks!
Sorry for the late reply, apparently I had my email notifications turned off.
Anyway, this solution worked perfectly and i corrected the temperature settings.
As for my GPU, i can confirm its 0 RPM as it only runs under load.

**Comment by iamanai** [comment]
Ah ok, good to know!
