### ISSUE TITLE
Persistent update notifications on latest version

### ISSUE THREAD

**Issue by ahmedwaill** [iamanai/ModernGadgets#43]
Hello , after the latest update there is a window keeps poping up tells that there is a new update but i already got the latest version so i hope that there is a solution for this pop up window it's kinda annoying.

**Comment by iamanai** [comment]
Are you on v1.2.1 or v1.2.2? I just released another patch a few hours ago because I accidentally broke something, so make certain you _actually_ have the latest version.

**Comment by iamanai** [comment]
If you are on v1.2.2 and the window keeps popping up, go into the global settings skin and disable "update notifications". This will stop it from happening.

**Comment by ahmedwaill** [comment]
ok

**Comment by ahmedwaill** [comment]
well, done thanks

**Comment by ahmedwaill** [comment]
btw did it and still popping up ..

**Comment by iamanai** [comment]
Huh, that is very odd. Right-click on Rainmeter's tray icon and select "About". Tell me what shows up there. In the meantime, the next time the update notification comes up, ctrl+right-click on it and select "Unload skin".

**Comment by ahmedwaill** [comment]
![2017-08-04_125744](https://user-images.githubusercontent.com/30704271/28966099-977b2880-7914-11e7-874b-b01e3cdf7ba3.png)
i just updated the Program it self now but still getting this popup window

**Comment by ahmedwaill** [comment]
After Updating Rainmeter it self  got this error ... 
![2017-08-04_125959](https://user-images.githubusercontent.com/30704271/28966141-e0607118-7914-11e7-9910-40ca2a690ebd.png)

**Comment by ahmedwaill** [comment]
> the next time the update notification comes up, ctrl+right-click on it and select "Unload skin".
when i did this it didn't apear again

**Comment by iamanai** [comment]
Yeah, the update notifications come from another skin, called "setup". It constantly runs in the background, checking for updates every 30 mins or so. It's definitely a bug with that skin.

**Comment by ahmedwaill** [comment]
ok hope u fix it

**Comment by iamanai** [comment]
Wait, hold on... I see the problem. What is this "Elrays" thing? Everything should be under ModernGadgets. If they're not, stuff breaks.

**Comment by ahmedwaill** [comment]
well i was just trying to do something by Copying Codes and trying to make 1 Modified to fit me ,
but it's another thing not ModernGadget ones

**Comment by iamanai** [comment]
That's the problem. The setup skin is wigging out because it's not in the ModernGadgets folder. That's why it is constantly popping up for you.

**Comment by ahmedwaill** [comment]
but it's not ModernGadget and i'm not even loading the skin

**Comment by ahmedwaill** [comment]
i deleted it hope that fixes the problem

**Comment by iamanai** [comment]
Well, looking st the log, you somehow have a ModernGadgets setup skin in the Elrayes folder. This is the one that is freaking out. You also have a setup skin in the ModernGadgets folder itself that is working just fine. So as long as you have unloaded the one in the Elrayes folder, you should be fine now.

**Comment by ahmedwaill** [comment]
i've deleted it but it was already unloaded i'venot loaded it before cuz it wasn't working Properly

**Comment by iamanai** [comment]
Well it shouldn't happen any more, so I'm closing this issue. If you ever have problems again with this be sure to let me know. Sorry about that!
